import type { ReportData } from '../types/report.js';
import type { SeoCheckResult } from '../types/check-result.js';

/**
 * Generates a "Dev Bug Report": a single Markdown document a tester can hand
 * straight to a developer (or paste directly into Claude/another AI coding
 * assistant) after a Blog Testing / SEO QA run, so every content mismatch
 * can be fixed without the developer having to open this tool at all.
 *
 * Deliberately minimal: each issue is just its check name, an Expected line,
 * and an Actual line — nothing else. No prose hints, no diff blocks, no
 * emoji, no machine-readable JSON. A short check name plus expected/actual
 * text is everything both a developer and an LLM need to locate and fix the
 * mismatch on the live page.
 *
 * Explicitly scoped to the LIVE PAGE, not this framework's own source — the
 * fixes described here belong in the website/CMS that renders the audited
 * URL, not in the seo-qa-framework codebase.
 *
 * Pure presentation over the existing ReportData shape — no new comparison
 * logic, so it can never change what passes or fails.
 */
export function generateDevBugReport(reportData: ReportData, options: { url?: string } = {}): string {
  const { summary, seoCheckResults } = reportData;
  const isBlog = summary.kind === 'blog';

  // A blog run (or any run the caller pins to one specific URL) always
  // describes a single page — keep the existing "one Live URL line, never
  // repeated per issue" behaviour exactly. A sheet run can span many pages
  // (every SEO audit sheet already could; FAQ-accordion sheets make it the
  // common case), so when the results actually span more than one distinct
  // URL and the caller didn't pin one, there's no single "Live URL" to
  // print — show a page count instead, and annotate each finding with the
  // specific page it belongs to so nothing reads as ambiguous.
  const distinctResultUrls = [...new Set(seoCheckResults.map((r) => r.url).filter(Boolean))];
  const singleUrl = options.url ?? (distinctResultUrls.length <= 1 ? distinctResultUrls[0] : undefined);
  const showUrlPerIssue = !singleUrl;

  const lines: string[] = [];

  const failed   = seoCheckResults.filter((r) => r.status === 'failed');
  const warnings = seoCheckResults.filter((r) => r.status === 'warning');
  const passed   = seoCheckResults.filter((r) => r.status === 'passed');

  lines.push(isBlog ? '# Blog Content Bug Report' : '# SEO Audit Bug Report', '');
  lines.push(
    isBlog
      ? 'Generated by the SEO QA Framework\'s Blog Testing tool. This report describes mismatches between an ' +
        'approved content document and what is actually live on the website below. Every fix described here ' +
        'belongs in the website/CMS that serves the live URL, not in the seo-qa-framework tool itself.'
      : 'Generated by the SEO QA Framework\'s Website SEO Audit tool. This report describes issues found on the ' +
        'live page(s) below versus what the audit sheet expected. Every fix described here belongs in the ' +
        'website/CMS that serves each page, not in the seo-qa-framework tool itself.',
    ''
  );

  if (singleUrl) {
    lines.push(`Live URL: ${singleUrl}`);
  } else {
    lines.push(`Pages tested: ${distinctResultUrls.length}`);
  }
  lines.push(`${isBlog ? 'Approved source document' : 'Audit sheet'}: ${basename(summary.sourcePath)}`);
  lines.push(`Tested: ${summary.generatedAt}`);
  lines.push(`Result: ${failed.length} Failed, ${warnings.length} Warning${warnings.length === 1 ? '' : 's'}, ${passed.length} Passed`);
  lines.push('');

  if (failed.length === 0 && warnings.length === 0) {
    lines.push('No issues found. Every check in this run passed — nothing for a developer to fix.', '');
    return lines.join('\n');
  }

  if (failed.length > 0) {
    lines.push('## Must Fix', '');
    for (const result of failed) lines.push(...renderIssue(result, showUrlPerIssue));
  }

  if (warnings.length > 0) {
    lines.push('## Warnings', '');
    for (const result of warnings) lines.push(...renderIssue(result, showUrlPerIssue));
  }

  lines.push('## Passed', '');
  if (passed.length === 0) {
    lines.push('None.', '');
  } else {
    lines.push(`${passed.length} check(s) already match the approved document: ${passed.map((r) => r.checkType).join(', ')}`, '');
  }

  return lines.join('\n');
}

// ── Rendering ────────────────────────────────────────────────────────────────────

function renderIssue(result: SeoCheckResult, showUrl: boolean): string[] {
  const lines: string[] = [];
  lines.push(showUrl ? `### ${result.checkType} — ${result.url}` : `### ${result.checkType}`);
  lines.push(`Expected: ${result.expected ?? '(none)'}`);
  lines.push(`Actual: ${result.actual ?? '(missing from the live page)'}`);
  lines.push('');
  return lines;
}

// ── Shared helpers ─────────────────────────────────────────────────────────────

function basename(filePath: string): string {
  const normalized = filePath.replace(/\\/g, '/');
  const segments = normalized.split('/');
  return segments[segments.length - 1] ?? filePath;
}
