import type { ReportData } from '../types/report.js';
import type { DiffSegment, SeoCheckResult } from '../types/check-result.js';

/**
 * Generates a "Dev Bug Report": a single Markdown document a tester can hand
 * straight to a developer (or paste directly into Claude/another AI coding
 * assistant) after a Blog Testing / SEO QA run, so every content mismatch
 * can be fixed without the developer having to open this tool at all.
 *
 * Design goals:
 *  - Human-readable: grouped by severity then category, plain expected-vs-
 *    actual text, no jargon from this tool's internals.
 *  - AI-actionable: every issue is a self-contained block (what, where,
 *    expected, actual, a git-style diff) with nothing implied by row order
 *    or table position — an LLM reading just one block has everything it
 *    needs. A machine-readable JSON array of the same issues is appended at
 *    the end for tooling that wants to parse rather than read.
 *  - Explicitly scoped to the LIVE PAGE, not this framework's own source —
 *    the fixes described here belong in the website/CMS that renders the
 *    audited URL, not in the seo-qa-framework codebase.
 *
 * Pure presentation over the existing ReportData shape — no new comparison
 * logic, so it can never change what passes or fails.
 */
export function generateDevBugReport(reportData: ReportData, options: { url?: string } = {}): string {
  const { summary, seoCheckResults } = reportData;
  const url = options.url ?? seoCheckResults[0]?.url;
  const lines: string[] = [];

  const failed   = seoCheckResults.filter((r) => r.status === 'failed');
  const warnings = seoCheckResults.filter((r) => r.status === 'warning');
  const passed   = seoCheckResults.filter((r) => r.status === 'passed');

  lines.push('# 🐛 Blog Content Bug Report', '');
  lines.push(
    '> Generated by the SEO QA Framework\'s Blog Testing tool. This report describes mismatches between an ' +
    'approved content document and what is actually live on the website below. **Every fix described here ' +
    'belongs in the website/CMS that serves the live URL — not in the seo-qa-framework tool itself.**',
    ''
  );

  lines.push('## Overview', '');
  if (url) lines.push(`- **Live URL:** ${url}`);
  lines.push(`- **Approved source document:** \`${basename(summary.sourcePath)}\``);
  lines.push(`- **Tested:** ${summary.generatedAt}`);
  lines.push(`- **Result:** ${statusBadge(failed.length, warnings.length, passed.length)}`);
  lines.push('');

  if (failed.length === 0 && warnings.length === 0) {
    lines.push('✅ **No issues found.** Every check in this run passed — nothing for a developer to fix.', '');
    return lines.join('\n');
  }

  lines.push(
    `This blog has **${failed.length} issue${failed.length === 1 ? '' : 's'} that must be fixed** and ` +
    `**${warnings.length} warning${warnings.length === 1 ? '' : 's'}** worth a quick look. ${passed.length} other ` +
    'check(s) already match the approved document and need no action.',
    ''
  );

  if (failed.length > 0) {
    lines.push('---', '', '## 🔴 Must Fix', '');
    lines.push(...renderGroupedIssues(failed, 'failed'));
  }

  if (warnings.length > 0) {
    lines.push('---', '', '## 🟡 Worth Reviewing (non-blocking)', '');
    lines.push(...renderGroupedIssues(warnings, 'warning'));
  }

  lines.push('---', '', '## ✅ Already Correct', '');
  if (passed.length === 0) {
    lines.push('None — see the issues above.', '');
  } else {
    lines.push(
      `${passed.length} check(s) already match the approved document and need no changes: ` +
      passed.slice(0, 12).map((r) => `\`${r.checkType}\``).join(', ') +
      (passed.length > 12 ? `, and ${passed.length - 12} more.` : '.'),
      ''
    );
  }

  lines.push('---', '', '## 🤖 Machine-Readable Issue Data', '');
  lines.push(
    'The same issues above, as structured JSON — one object per issue, in the same must-fix-then-warning order. ' +
    'Use this if you are scripting a fix or feeding it to another tool; each issue is already fully described in the ' +
    'sections above for direct reading.',
    ''
  );
  lines.push('```json');
  lines.push(JSON.stringify([...failed, ...warnings].map(toMachineIssue), null, 2));
  lines.push('```', '');

  return lines.join('\n');
}

// ── Grouping & rendering ────────────────────────────────────────────────────────

interface IssueGroup {
  category: string;
  actionHint: string;
  results: SeoCheckResult[];
}

/** Where in the live page this class of content generally lives, and the generic shape of the fix — deliberately generic since this tool has no knowledge of the target site's actual codebase/CMS. */
const CATEGORY_ACTION_HINTS: ReadonlyArray<{ match: (checkType: string) => boolean; category: string; actionHint: string }> = [
  {
    match: (t) => t === 'Meta Title' || t === 'Meta Description' || t === 'Blog Title (H1)',
    category: 'Metadata',
    actionHint: 'Update the page\'s `<title>`/`<meta name="description">` tag or H1 in the CMS/template to match the approved text exactly (minor trailing punctuation differences are fine).'
  },
  {
    match: (t) => /^H[234] #\d+$/.test(t),
    category: 'Headings',
    actionHint: 'Update the heading text in the page content/CMS editor to match the approved document, or move it back into the expected position if it has simply been reordered.'
  },
  {
    match: (t) => t.startsWith('"'),
    category: 'Paragraphs',
    actionHint: 'Update the paragraph text in the page content/CMS editor to match the approved document.'
  },
  {
    match: (t) => t.startsWith('Hyperlink'),
    category: 'Hyperlinks',
    actionHint: 'Fix the anchor text and/or the href destination for this link in the page content so it exactly matches the approved (text, URL) pair.'
  },
  {
    match: (t) => t.startsWith('Bold'),
    category: 'Bold Text',
    actionHint: 'Add or remove `<strong>`/`<b>` formatting around this text in the page content editor.'
  },
  {
    match: (t) => t === 'Canonical URL' || t === 'Blog URL / Slug',
    category: 'URL & Canonical',
    actionHint: 'Update the `<link rel="canonical">` tag or the page\'s URL/slug/redirect configuration to match the approved value.'
  }
];

function categorize(checkType: string): { category: string; actionHint: string } {
  const found = CATEGORY_ACTION_HINTS.find(({ match }) => match(checkType));
  return found
    ? { category: found.category, actionHint: found.actionHint }
    : { category: 'Other', actionHint: 'Review this check against the approved document and update the live page to match.' };
}

function renderGroupedIssues(results: readonly SeoCheckResult[], severity: 'failed' | 'warning'): string[] {
  const groups = new Map<string, IssueGroup>();
  for (const result of results) {
    const { category, actionHint } = categorize(result.checkType);
    const group = groups.get(category) ?? { category, actionHint, results: [] };
    group.results.push(result);
    groups.set(category, group);
  }

  const lines: string[] = [];
  let counter = 0;
  for (const group of groups.values()) {
    lines.push(`### ${group.category} (${group.results.length})`, '');
    lines.push(`_Where to look: ${group.actionHint}_`, '');
    for (const result of group.results) {
      counter++;
      lines.push(...renderIssue(counter, result, severity));
    }
  }
  return lines;
}

function renderIssue(index: number, result: SeoCheckResult, severity: 'failed' | 'warning'): string[] {
  const icon = severity === 'failed' ? '❌' : '⚠️';
  const lines: string[] = [];

  lines.push(`#### ${index}. ${icon} ${result.checkType}`, '');
  lines.push(`- **URL:** ${result.url}`);
  if (result.expected !== undefined) lines.push(`- **Expected (approved document):** ${inlineCode(result.expected)}`);
  if (result.actual !== undefined)   lines.push(`- **Actual (live page):** ${inlineCode(result.actual)}`);
  if (result.message) lines.push(`- **Issue:** ${result.message}`);

  const diffBlock = renderDiffBlock(result);
  if (diffBlock) lines.push('- **Diff:**', '', ...diffBlock);

  lines.push('');
  return lines;
}

/**
 * Renders a git-style unified diff block (`-`/`+` lines) so the change is
 * visually obvious to a human skimming the report and trivially parseable
 * by an LLM already trained on diff syntax. Falls back to the plain
 * expected/actual pair when no structured word-level diff was computed
 * (e.g. a hyperlink or bold-phrase mismatch) — omitted entirely when there
 * is no `actual` value to compare against (content reported as missing).
 */
function renderDiffBlock(result: SeoCheckResult): string[] | undefined {
  if (result.actual === undefined || result.expected === undefined) return undefined;
  // Identical text (e.g. a paragraph/heading reported as "moved" but
  // otherwise unchanged) has nothing to diff — a diff block would just be
  // visual noise repeating the same line twice.
  if (result.expected === result.actual) return undefined;

  const lines = ['```diff', `- ${result.expected}`, `+ ${result.actual}`];

  const wordChanges = summarizeWordLevelChanges(result.diff);
  if (wordChanges.length > 0) {
    lines.push('', `# Word-level change${wordChanges.length === 1 ? '' : 's'}: ${wordChanges.join('; ')}`);
  }

  lines.push('```');
  return lines;
}

function summarizeWordLevelChanges(diff: DiffSegment[] | undefined): string[] {
  if (!diff || diff.length === 0) return [];
  return diff
    .filter((segment) => segment.type !== 'same')
    .map((segment) => {
      if (segment.type === 'changed') return `"${segment.expected}" → "${segment.actual}"`;
      if (segment.type === 'removed') return `removed "${segment.expected}"`;
      return `added "${segment.actual}"`;
    });
}

/** A curated, flat issue shape for the machine-readable JSON block — every field an automated fix needs, nothing this tool considers internal bookkeeping. */
function toMachineIssue(result: SeoCheckResult): Record<string, unknown> {
  const { category } = categorize(result.checkType);
  return {
    severity: result.status,
    category,
    checkType: result.checkType,
    url: result.url,
    expected: result.expected,
    actual: result.actual,
    message: result.message,
    diff: result.diff
  };
}

// ── Shared helpers ─────────────────────────────────────────────────────────────

function statusBadge(failedCount: number, warningCount: number, passedCount: number): string {
  return `❌ ${failedCount} Failed · ⚠️ ${warningCount} Warning${warningCount === 1 ? '' : 's'} · ✅ ${passedCount} Passed`;
}

function inlineCode(value: string): string {
  // A backtick inside the value would otherwise prematurely close the code span.
  return value.includes('`') ? `"${value}"` : `\`${value}\``;
}

function basename(filePath: string): string {
  const normalized = filePath.replace(/\\/g, '/');
  const segments = normalized.split('/');
  return segments[segments.length - 1] ?? filePath;
}
