import type { ReportData } from '../types/report.js';
import type { SeoCheckResult } from '../types/check-result.js';

/**
 * Generates a "Dev Bug Report": a single Markdown document a tester can hand
 * straight to a developer (or paste directly into Claude/another AI coding
 * assistant) after a Blog Testing / SEO QA run, so every content mismatch
 * can be fixed without the developer having to open this tool at all.
 *
 * Deliberately minimal: each issue is just its check name, an Expected line,
 * and an Actual line — nothing else. No prose hints, no diff blocks, no
 * emoji, no machine-readable JSON. A short check name plus expected/actual
 * text is everything both a developer and an LLM need to locate and fix the
 * mismatch on the live page.
 *
 * Explicitly scoped to the LIVE PAGE, not this framework's own source — the
 * fixes described here belong in the website/CMS that renders the audited
 * URL, not in the seo-qa-framework codebase.
 *
 * Pure presentation over the existing ReportData shape — no new comparison
 * logic, so it can never change what passes or fails.
 */
export function generateDevBugReport(reportData: ReportData, options: { url?: string } = {}): string {
  const { summary, seoCheckResults } = reportData;
  const url = options.url ?? seoCheckResults[0]?.url;
  const lines: string[] = [];

  const failed   = seoCheckResults.filter((r) => r.status === 'failed');
  const warnings = seoCheckResults.filter((r) => r.status === 'warning');
  const passed   = seoCheckResults.filter((r) => r.status === 'passed');

  lines.push('# Blog Content Bug Report', '');
  lines.push(
    'Generated by the SEO QA Framework\'s Blog Testing tool. This report describes mismatches between an ' +
    'approved content document and what is actually live on the website below. Every fix described here ' +
    'belongs in the website/CMS that serves the live URL, not in the seo-qa-framework tool itself.',
    ''
  );

  if (url) lines.push(`Live URL: ${url}`);
  lines.push(`Approved source document: ${basename(summary.sourcePath)}`);
  lines.push(`Tested: ${summary.generatedAt}`);
  lines.push(`Result: ${failed.length} Failed, ${warnings.length} Warning${warnings.length === 1 ? '' : 's'}, ${passed.length} Passed`);
  lines.push('');

  if (failed.length === 0 && warnings.length === 0) {
    lines.push('No issues found. Every check in this run passed — nothing for a developer to fix.', '');
    return lines.join('\n');
  }

  if (failed.length > 0) {
    lines.push('## Must Fix', '');
    for (const result of failed) lines.push(...renderIssue(result));
  }

  if (warnings.length > 0) {
    lines.push('## Warnings', '');
    for (const result of warnings) lines.push(...renderIssue(result));
  }

  lines.push('## Passed', '');
  if (passed.length === 0) {
    lines.push('None.', '');
  } else {
    lines.push(`${passed.length} check(s) already match the approved document: ${passed.map((r) => r.checkType).join(', ')}`, '');
  }

  return lines.join('\n');
}

// ── Rendering ────────────────────────────────────────────────────────────────────

function renderIssue(result: SeoCheckResult): string[] {
  const lines: string[] = [];
  lines.push(`### ${result.checkType}`);
  lines.push(`Expected: ${result.expected ?? '(none)'}`);
  lines.push(`Actual: ${result.actual ?? '(missing from the live page)'}`);
  lines.push('');
  return lines;
}

// ── Shared helpers ─────────────────────────────────────────────────────────────

function basename(filePath: string): string {
  const normalized = filePath.replace(/\\/g, '/');
  const segments = normalized.split('/');
  return segments[segments.length - 1] ?? filePath;
}
